# Generated by Django 6.0.4 on 2026-04-16 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring'), ('writing', 'Writing / Editing'), ('design', 'Design / Media'), ('tech', 'Tech / Programming'), ('other', 'Other')], max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Set the price or choose free.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('free', models.BooleanField(default=False, help_text='Mark this skill as free if you do not want payment.')),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat / DM')], max_length=16)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('scheduled', 'Scheduled')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
