# Generated by Django 6.0.4 on 2026-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('scheduled', 'Scheduled')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tutoring', 'Tutoring'), ('writing', 'Writing / Editing'), ('design', 'Design / Media'), ('tech', 'Tech / Programming'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='free',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this skill as free if you do not want payment.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
